import { AurixProductGrid } from '../../components/aurix/AurixProductGrid';

// Sample AURIX products - these will be replaced with real data
const aurixProducts = [
  {
    id: 'aurix-1',
    name: 'Cyber Fashion',
    price: 99.99,
    description: 'AI-generated cyber fashion design'
  },
  {
    id: 'aurix-2',
    name: 'Neon Samurai Streetwear', 
    price: 159.99,
    description: 'AI-generated streetwear design'
  },
  {
    id: 'aurix-3',
    name: 'Holographic Rave Dress',
    price: 149.99,
    description: 'AI-generated rave fashion'
  },
  {
    id: 'aurix-4',
    name: 'Tactical Streetwear Vest',
    price: 89.99,
    description: 'AI-generated tactical fashion'
  },
  {
    id: 'aurix-5',
    name: 'Quantum Silk Dress',
    price: 179.99,
    description: 'AI-generated luxury fashion'
  },
  {
    id: 'aurix-6', 
    name: 'Urban Tactical Pants',
    price: 89.99,
    description: 'AI-generated urban fashion'
  }
];

export default function AurixPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="text-center mb-8">
        <h1 className="text-4xl font-bold mb-4">AURIX AI Fashion</h1>
        <p className="text-xl text-gray-600">
          Discover unique fashion designs generated by artificial intelligence
        </p>
      </div>
      
      <AurixProductGrid products={aurixProducts} />
      
      <div className="bg-gray-100 rounded-lg p-6 text-center">
        <h3 className="text-lg font-semibold mb-2">Powered by RISN + AURIX</h3>
        <p className="text-gray-600">
          Each design is uniquely generated using advanced AI models
        </p>
      </div>
    </div>
  );
}
